Todo UI
Keiji-morita/todo_for_Traial pull request #7
Opened 2022-05-25 19:18 UTC by Keiji-morita

メモ追加機能実装しました。issueで出してたとこフル無視して結局写経とコピペで乗り切ってしまいました。。。

2022-05-25 19:31 UTC, Keiji-morita commented
dismissibleを使ってtodoカードをスライドすると削除できる機能も実装しました
<img width="1440" alt="スクリーンショット 2022-05-26 4 31 05" src="https://user-images.githubusercontent.com/87302097/170352572-602dc9e4-e66f-42d0-aa86-067958bb0aa0.png">
。

2022-05-26 05:32 UTC, mine2424 requested changes
レビューしたよ！

2022-05-26 05:32 UTC, mine2424 commented on lib/todo_list.dart
> +  List<Todo> _todos = [
これは、仮のデータ？
まだ、Firebase連携はできていない感じかな？

2022-05-26 05:32 UTC, mine2424 commented on lib/todo_list.dart
> +                            onDismissed: (DismissDirection direction) {
所々、フォーマットずれてるところがあるからcommitする前にフォマットしといてね！

2022-05-26 05:32 UTC, mine2424 commented on lib/todo_list.dart
> +class Todo {
ここにクラスを定義するのはあまり良くないかも。。。
できたら`model/~`内に入れるといいかも！
あと、できたら再代入不可(=immutable)のクラスを書くといいよ！
```dart
// ex)
@immutable
class Todo {
  final String title;
  final bool isDone;
  Todo({
    required this.title,
    required this.isDone,
  });

  Todo copyWith({
    String? title,
    bool? isDone,
  }) {
    return Todo(
      title: title ?? this.title,
      isDone: isDone ?? this.isDone,
    );
  }
}
```

2022-05-26 05:32 UTC, mine2424 commented on lib/todo_list.dart
> +    bool done;
bool値は基本的にIs~とかにした方がいいかも！
`isDone`とかね

2022-05-27 05:04 UTC, Keiji-morita commented on lib/todo_list.dart
> +  List<Todo> _todos = [
ここではまだfirebaseの連携はやってないです！

2022-05-28 08:55 UTC, merged